language: go
go:
  - "1.10"
  - "1.11"
  - master

install: true

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s vX.Y.Z

script:
  - golangcli-lint run
  - go test -v ./...